drupal:
  #image: drupal:8.0.0
  build: ./drupal
  expose:
    - "80"
  ports:
    - "8080:80"
  links:
    - drupalmysql
  environment:
    - DB_NAME=drupal
    - DB_USER=drupal
    - DB_PASSWORD=drupal
drupalmysql:
  image: mysql:5.6
  
  environment:
    - MYSQL_DATABASE=drupal
    - MYSQL_USER=drupal
    - MYSQL_PASSWORD=drupal
    - MYSQL_ROOT_PASSWORD=superdupersecret
  ports:
    - "32770:3306"
  expose:
    - "3306"  
